#import "../Template/canvas-html.typ": *
#import "@preview/numbly:0.1.0": numbly

#show: canvas-html.with(
  course-id: "1067114",
  image-ids: (
    "Decomposition.png" : "31361277",
    "Parabola.svg" : "31361279",
    "Revenue.svg" : "31361280"
  ),
  title: "MAT 21C Discussion 10",
  author: "Chen Liang",
  date: datetime(year: 2026, month: 6, day: 1),
)

= Warm-Up

#exercise(label: [Warm-up])[
  Suppose that every minute of advertising on TV costs #mi(`2`) dollars and every minute of advertising on podcast costs #mi(`1`) dollar.
  Consider the following scenarios of marginal revenue generated by each minute of advertising on TV and podcast:
  #set enum(numbering: numbly("Scenario {1}:"))
  + The last minute of advertising on TV generated #mi(`16`) dollars in revenue and the last minute of advertising on podcast generated #mi(`2`) dollars in revenue.
  + The last minute of advertising on TV generated #mi(`4`) dollars in revenue and the last minute of advertising on podcast generated #mi(`8`) dollars in revenue.
  + The last minute of advertising on TV generated #mi(`10`) dollars in revenue and the last minute of advertising on podcast generated #mi(`5`) dollars in revenue.
  We have fixed advertising budget, so spending more on TV means spending less on podcast and vice versa.
  In each of the scenarios, determine how should we adjust our advertising strategy to maximize the revenue.
]
#solution[
  In Scenario 1, advertising on TV has the marginal revenue of #mi(`8`) dollars per dollar spent, while advertising on podcast has the marginal revenue of #mi(`2`) dollars per dollar spent, so we should spend more on TV and less on podcast to increase the revenue.
  To be more specific, we can spend #mi(`2`) dollars more on TV to get #mi(`16`) dollars in revenue while cutting down #mi(`2`) dollars (cutting #mi(`2`) minutes) from podcast only reduces the revenue by #mi(`4`) dollars.

  In Scenario 2, advertising on TV has the marginal revenue of #mi(`2`) dollars per dollar spent, while advertising on podcast has the marginal revenue of #mi(`8`) dollars per dollar spent, so we should spend more on podcast and less on TV to increase the revenue.

  In Scenario 3, both advertising on TV and podcast have the same marginal revenue of #mi(`5`) dollars per dollar spent, so perhaps we are already at the optimal strategy!
  No further adjustment needed based on the marginal revenue report.
]

The crucial takeaway is that we might be at the optimal strategy only when the marginal revenue per dollar spent is the same for both TV and podcast, or in other words, we obtain the same common factor #mi(`\lambda`) when we
- divide the marginal revenue of TV by its cost, and
- divide the marginal revenue of podcast by its cost.
This is at the heart of the Lagrange multiplier method.

= Lagrange Multipliers

The warm-up problem is an example of a constrained optimization problem where we want to find the optimal
- minutes of advertising on TV (#mi(`x`)) and
- minutes of advertising on podcast (#mi(`y`))
to maximize a revenue function #mi(`f(x, y)`) under the constraint of a fixed budget #mi(`g(x, y) = c`).

The particular problem in the warm-up is derived from the setup that the revenue function is #mi(`f(x, y) = x y`) and the budget constraint is #mi(`g(x, y) = 2 x + y = 20`).
Stripping away the context, we just want to maximize the function #mi(`f(x, y)`) under the constraint #mi(`g(x, y) = c`), the Lagrange multiplier method tells us to write down
#mitex(```
\begin{cases}
\nabla f(x, y) = \lambda \nabla g(x, y), \\
g(x, y) = c,
\end{cases}
```)
and solve for the three numbers #mi(`x`), #mi(`y`), and #mi(`\lambda`).
The first is actually two equations, one for the #mi(`x`)-component and one for the #mi(`y`)-component of the gradients, so really we have three equations
#mitex(```
\begin{cases}
f_x(x, y) = \lambda g_x(x, y), \\
f_y(x, y) = \lambda g_y(x, y), \\
g(x, y) = c.
\end{cases}
```)
For our problem, we have
#mitex(```
\begin{cases}
y = 2 \lambda, \\
x = \lambda, \\
2 x + y = 20.
\end{cases}
```)
The first two equations tell us that #mi(`y = 2x`), and plugging this into the third equation gives #mi(`4x = 20`), so #mi(`x = 5`).
Then we can easily find that #mi(`y = 10`) and #mi(`\lambda = 5`).
This means that the #mi(`(5, 10)`) is a critical point and hence is a candidate for the maximum.
To really confirm that it is the maximum, we need to check all candidates which include the critical points and the boundary points.
The boundary points correspond to
- spending all on TV, which is #mi(`(10, 0)`), and
- spending all on podcast, which is #mi(`(0, 20)`).
In our model, the revenue function #mi(`f(x,y) = xy`) is actually #mi(`0`) if we spend all on one thing, so the boundary points are actually the minima.
The maximum is achieved at #mi(`(5, 10)`) (having #mi(`5`) minutes of TV ads and #mi(`10`) minutes of podcast ads) and the revenue is #mi(`f(5, 10) = 50`).

To understand, why Lagrange multipliers work, let us look at the plot of #mi(`f(x, y)`) and #mi(`g(x, y) = 20`).
#figure(
  image(
    "Revenue.svg",
    width: 40%,
    alt: "Hyperbolic gray contours and a red line tangent to one of the contours. Blue vectors, perpendicular to the contours, have components toward the point of tangency.",
  ),
  caption: [
    The constraint #mi(`g(x, y) = 20`) is the red line, and the contours of the revenue function #mi(`f(x, y)`) are the gray curves.
    The blue vectors are the gradients of #mi(`f(x, y)`) while the red arrows are the gradients of #mi(`g(x, y)`).
  ],
)
The gradients of #mi(`f(x, y)`) represent the marginal revenue report because for example
#mitex(```
f = \text{revenue}, \quad
x = \text{minutes of TV ads} \quad
\implies \quad
\frac{\partial f}{\partial x} = \text{revenue per minute of TV ads}.
```)
When the gradient of #mi(`f`) is not proportional to the gradient of #mi(`g`), then that means it has nonzero projection onto the constraint surface, and as we move in that direction along the surface, we will increase #mi(`f`).
For example, at the point #mi(`(2, 16)`), the blue vector is trying to drag the point to the right.
This is the analogous statement for saying that the "marginal revenue vector" is not proportional to the "marginal cost vector", it shows that TV ads are more profitable, so we should spend more on TV ads.

#exercise[
  + The graph below shows the parabola #mi(`y = x^2 + 4x + 6`) and the line #mi(`y = 2x`).
    Discuss why the point on the parabola that is closest to the line must have a tangent line with the same slope.
    Can you easily find the point?
    #figure(
      image(
        "Parabola.svg",
        width: 30%,
        alt: "A red parabola and a blue line. A dashed tangent line to the parabola is parallel to the blue line.",
      ),
      caption: [
        The red parabola is #mi(`y = x^2 + 4x + 6`) and the blue line is #mi(`y = 2x`).
        The point on the parabola that is closest to the line is drawn along with the tangent line at that point.
      ],
    )
  + Find the minimum and maximum of the function #mi(`f(x, y) = x^2 + 2 y^2 - x`) on the unit circle #mi(`x^2 + y^2 = 1`).
    _Hint:_ #mi(`ab = 0`) implies that either #mi(`a = 0`) or #mi(`b = 0`).
]
#solution[
  + The level curves of the distance function from the line #mi(`y = 2x`) are lines parallel to it.
    Visually from the graph, we can see that the point on the parabola closest to the line must have a tangent line parallel to the line #mi(`y = 2x`).
    For any other point on the parabola, the tangent line is not parallel to #mi(`y = 2x`), which means we can move in the direction of the tangent line to get closer to the line #mi(`y = 2x`).
    To find the point, we simply need to solve #mi(`2x + 4 = 2`), which yields #mi(`x = -1`), so the point is #mi(`(-1, 3)`).
  + Write the constraint as #mi(`g(x, y) = x^2 + y^2 = 1`), then we can find the critical points by solving
    #mitex(```
    \begin{cases}
    f_x (x, y) = \lambda g_x (x, y), \\
    f_y (x, y) = \lambda g_y (x, y), \\
    g(x, y) = 1,
    \end{cases}
    ```)
    which is
    #mitex(```
    \begin{cases}
    2x - 1 = 2 \lambda x, \\
    4y = 2 \lambda y, \\
    x^2 + y^2 = 1.
    \end{cases}
    ```)
    The second equation tells us #mi(`( 4 - 2 \lambda) y = 0`), so we either have #mi(`4 - 2 \lambda = 0`) or #mi(`y = 0`).
    - If #mi(`4 - 2 \lambda = 0`), then #mi(`\lambda = 2`), and plugging this into the first equation gives#h(100%)
      #mitex(```
      2x - 1 = 4 x \implies x = -\frac{1}{2}.
      ```)
      Then, the third equation gives
      #mitex(```
      y = \pm \frac{\sqrt{3}}{2}.
      ```)
      Both #mi(`(-\frac{1}{2}, \frac{\sqrt{3}}{2})`) and #mi(`(-\frac{1}{2}, -\frac{\sqrt{3}}{2})`) are critical points.
      The value of #mi(`f`) at these points is the same, which is
      #mitex(```
      \left(-\frac{1}{2}\right)^2 + 2 \left(\frac{\sqrt{3}}{2}\right)^2 - \left(-\frac{1}{2}\right) = \frac{9}{4}.
      ```)
    - If #mi(`y = 0`), then #mi(`x = \pm 1`) are both solutions (if #mi(`x = 1`), we can set #mi(`\lambda = 1/2`); and if #mi(`x = -1`), we can set #mi(`\lambda = 3/2`)).
      The values of #mi(`f`) at these points are
      #mitex(```
      f(1, 0) = 0 \quad \text{and} \quad f(-1, 0) = 2.
      ```)
    Therefore, the minimum of #mi(`f`) on the unit circle is #mi(`0`) and the maximum is #mi(`\frac{9}{4}`).
    #tip[
      This solution can be simplified slightly by noting that on the unit circle, we have
      #mitex(```
      f(x, y) = (x^2 + y^2) + y^2 - x = 1 + y^2 - x,
      ```)
      so we can equivalently find the extrema of #mi(`1 + y^2 - x`) instead.
      Lagrange multiplier method yields
      #mitex(```
      \begin{cases}
      -1 = 2 \lambda x, \\
      2y = 2 \lambda y, \\
      x^2 + y^2 = 1.
      \end{cases}
      ```)
      The second equation becomes #mi(`(2 - 2 \lambda) y = 0`), so we either have #mi(`\lambda = 1`) or #mi(`y = 0`).
      The analysis will continue in the same way as before.
      You can check that you will get the same critical points!

      This substitution technique is especially useful when the constraint curve is a line because we can substitute either #mi(`x`) or #mi(`y`) in terms of another to completely eliminate one variable and reduce the problem to a single variable optimization.
      For example, if the constraint is #mi(`x = 4`), then we can just set #mi(`x`) to #mi(`4`), and we would be optimizing a function of #mi(`y`);
      if the constraint is #mi(`y = 2x`), then we can set #mi(`y`) to #mi(`2x`), and we would be optimizing a function of #mi(`x`).
    ]
]

= Critical Points on Boundaries

In general, to find the extrema of a function on a closed and bounded region, we need to analyze the critical points in the interior and those on the boundary separately.
The boundary can often be decomposed again into multiple closed and bounded shapes, and we would need to recursively analyze them until we get down to points.

For example, to find the extrema of a function #mi(`f(x, y)`) on the half unit disk #mi(`x^2 + y^2 \leq 1`) and #mi(`y \geq 0`), we need to decompose it into #mi(`5`) pieces:
- The interior of the half unit disk.
- The upper semicircle without the endpoints #mi(`(-1, 0)`) and #mi(`(1, 0)`).
- The line segment from #mi(`(-1, 0)`) to #mi(`(1, 0)`) but without the end points.
- The point #mi(`(-1, 0)`).
- The point #mi(`(1, 0)`).
Then, we can apply different methods to different pieces.
- To find critical point in the interior of the half unit disk, we just need to solve #mi(`f_x (x, y) = 0`) and #mi(`f_y (x, y) = 0`) and pick the solutions that are in the interior.
- For the upper semicircle and the line segment, we can use Lagrange multiplier and/or substitution to find the critical points on them like we did in the previous section.
  For the line segment, it is really nice to use substitution #mi(`y = 0`), and for the upper semicircle, it is often nice to use Lagrange multiplier to avoid square roots.
- For the points, we just need to evaluate #mi(`f`) at those points.
After we find all the critical points and evaluate #mi(`f`) at those points, we can compare the values to find the minimum and maximum.

#figure(
  image(
    "Decomposition.png",
    width: 90%,
    alt: "Decomposition of a half unit disk into 5 pieces as described in the main text."
  ),
  caption: [
    The five pieces of the half unit disk labeled by the method we can use to find the critical points.
  ]
)

#exercise[
  + Find the minimum and maximum of the function #mi(`f(x, y) = x^2 + 2 y^2 - x`) on the unit disk #mi(`x^2 + y^2 \leq 1`).
  + Find the minimum and maximum of the function #mi(`f(x, y, z) = x^2 + 2 y^2 - x + z^2 - 2 z`) on the solid hemisphere #mi(`x^2 + y^2 + z^2 \leq 1`) with #mi(`z \geq 0`).
]
#solution[
  + We have already found the critical points of #mi(`f(x, y)`) on the boundary in the previous exercise.
    So now, we just need to check the critical points in the interior of the unit disk.
    The critical points in the interior are given by solving #mi(`f_x (x, y) = 0`) and #mi(`f_y (x, y) = 0`), which are
    #mitex(```
    2 x - 1 = 0 \quad \text{and} \quad 4 y = 0,
    ```)
    Thus, we have a critical point at #mi(`(\frac{1}{2}, 0)`), and the value of #mi(`f`) at this point is
    #mitex(```
    f\left(\frac{1}{2}, 0\right) = -\frac{1}{4}.
    ```)
    Thus, we have a new minimum.
    The maximum is still #mi(`\frac{9}{4}`) at the points #mi(`(-\frac{1}{2}, \pm \frac{\sqrt{3}}{2})`), but the minimum is now #mi(`-\frac{1}{4}`) at the point #mi(`(\frac{1}{2}, 0)`).
  + Notice that the base of the hemisphere is the unit disk in the #mi(`xy`)-plane and function on there evaluates to #mi(`f(x, y, 0) = x^2 + 2y^2 - x^2`).
    This is exactly the same setup as the previous part, so we just need to check the critical points in the interior of the hemisphere and those on the spherical boundary to see whether we need to update the minimum and maximum.

    The critical points in the interior of the hemisphere are given by solving #mi(`f_x (x, y, z) = 0`), #mi(`f_y (x, y, z) = 0`), and #mi(`f_z (x, y, z) = 0`), which are
    #mitex(```
    \begin{cases}
    2 x - 1 = 0, \\
    4 y = 0, \\
    2z - 2 = 0.
    \end{cases}
    ```)
    Therefore, we have #mi(`y = 0`), #mi(`x = \frac{1}{2}`), and #mi(`z = 1`), but this is not in the interior of the hemisphere, so we do not have any critical point in the interior.

    Now, we check the critical points on the spherical boundary.
    The constraint is #mi(`x^2 + y^2 + z^2 = 1`), so #mi(`f(x, y, z)`) on the boundary is #mi(`1 + y^2 - x - 2 z`), and we can find the critical points of this function on the boundary instead.
    We will use Lagrange multiplier method again, so we have
    #mitex(```
    \begin{cases}
    -1 = 2 \lambda x, \\
    2 y = 2 \lambda y, \\
    -2 = 2 \lambda z, \\
    x^2 + y^2 + z^2 = 1.
    \end{cases}
    ```)
    The second equation becomes #mi(`(2 - 2 \lambda) y = 0`), so we either have #mi(`\lambda = 1`) or #mi(`y = 0`).
    - If #mi(`\lambda = 1`), then the first and third equations yield #mi(`x = -\frac{1}{2}`) and #mi(`z = -1`), but there is no such point on the spherical boundary (no solution for #mi(`y`)), so we do not have any critical point from this case.
    - If #mi(`y = 0`), then we can find the ratio between the first and third equation to find that
      #mitex(```
      \frac{z}{x} = 2 \implies z = 2 x.
      ```)
      Using the constraint equation, we get
      #mitex(```
      x^2 + 4 x^2 = 1 \implies x = \pm \frac{1}{\sqrt{5}}.
      ```)
      If #mi(`x = -\frac{1}{\sqrt{5}}`), then #mi(`z = -\frac{2}{\sqrt{5}}`), which is not on the hemisphere (we need #mi(`z \geq 0`)), so the only critical point we get from this case is #mi(`(\frac{1}{\sqrt{5}}, 0, \frac{2}{\sqrt{5}})`).
      Evaluating #mi(`f`) at this point gives
      #mitex(```
      f\left(\frac{1}{\sqrt{5}}, 0, \frac{2}{\sqrt{5}}\right) = 1 - \frac{1}{\sqrt{5}} - \frac{4}{\sqrt{5}} = 1 - \sqrt{5}.
      ```)
      This is the new minimum (note that #mi(`\sqrt{5} > 2`)).
    Therefore, we once again have the same maximum #mi(`\frac{9}{4}`) at the points #mi(`(-\frac{1}{2}, \pm \frac{\sqrt{3}}{2}, 0)`), but we have a new minimum #mi(`1 - \sqrt{5}`) at the point #mi(`(\frac{1}{\sqrt{5}}, 0, \frac{2}{\sqrt{5}})`).
]
